"""Pydantic models for LLM-generated assembly instructions.

This module defines the structured output schemas expected from
the LLM, including assembly steps, safety warnings, and tool
recommendations.

Models:
    WarningSeverity: Enum for safety warning severity levels
    SafetyWarning: A safety warning with context and mitigation
    ToolRecommendation: Tool with purpose and alternatives
    AssemblyStep: Single step in assembly process
    TroubleshootingTip: Common issue with solution
    AssemblyInstructions: Complete assembly output from LLM
    AssemblyDeps: Dependencies injected into the agent
"""

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# Import domain types for AssemblyDeps - these are needed at runtime
# for Pydantic to properly validate the model
from cabinets.domain.entities import Cabinet
from cabinets.domain.value_objects import CutPiece, MaterialType

if TYPE_CHECKING:
    pass  # Keep TYPE_CHECKING block for potential future type-only imports


class WarningSeverity(str, Enum):
    """Severity levels for safety warnings.

    Used to categorize safety warnings by their importance level.
    DANGER warnings are never omitted regardless of skill level.

    Attributes:
        INFO: Helpful information, not critical
        CAUTION: Potential issue if not careful
        WARNING: Risk of damage or injury
        DANGER: Serious risk, critical to address
    """

    INFO = "info"
    CAUTION = "caution"
    WARNING = "warning"
    DANGER = "danger"


class SafetyWarning(BaseModel):
    """A safety warning with severity and context.

    Generated by the LLM to provide context-aware safety guidance
    based on the specific tools and materials in the project.

    Attributes:
        severity: Importance level of the warning
        message: The warning message text
        context: When/where this warning applies
        mitigation: How to address or avoid the hazard
    """

    severity: WarningSeverity
    message: str = Field(description="The warning message")
    context: str = Field(description="When/where this warning applies")
    mitigation: str = Field(description="How to address or avoid the hazard")


class ToolRecommendation(BaseModel):
    """A tool recommendation with alternatives.

    Provides tool guidance tailored to what the project actually requires,
    with alternative options for users without specific tools.

    Attributes:
        tool: Primary tool name
        purpose: What this tool is used for in this project
        alternatives: Alternative tools that could be used
        required: Whether this tool is required vs optional
    """

    tool: str = Field(description="Primary tool name")
    purpose: str = Field(description="What this tool is used for")
    alternatives: list[str] = Field(
        default_factory=list, description="Alternative tools that could be used"
    )
    required: bool = Field(
        default=True, description="Whether this tool is required vs optional"
    )


class AssemblyStep(BaseModel):
    """A single step in the assembly process.

    Contains all information needed for one assembly step,
    including skill-level-appropriate detail.

    Attributes:
        step_number: Sequential step number (starts at 1)
        phase: Assembly phase name (e.g., 'Carcase Assembly')
        title: Brief title for this step
        description: Detailed step instructions
        pieces_involved: Labels of cut pieces used in this step
        joinery_details: Joinery-specific instructions if applicable
        time_estimate: Estimated time for this step
        difficulty: Difficulty rating for this step
        quality_check: How to verify this step was done correctly
        common_mistakes: Common mistakes to avoid
    """

    step_number: int = Field(ge=1, description="Sequential step number")
    phase: str = Field(description="Assembly phase (e.g., 'Carcase Assembly')")
    title: str = Field(description="Brief title for this step")
    description: str = Field(description="Detailed step instructions")
    pieces_involved: list[str] = Field(description="Labels of pieces used in this step")
    joinery_details: str | None = Field(
        default=None, description="Joinery-specific instructions if applicable"
    )
    time_estimate: str | None = Field(
        default=None, description="Estimated time for this step"
    )
    difficulty: Literal["easy", "moderate", "challenging"] | None = Field(
        default=None, description="Difficulty rating for this step"
    )
    quality_check: str | None = Field(
        default=None, description="How to verify this step was done correctly"
    )
    common_mistakes: list[str] = Field(
        default_factory=list, description="Common mistakes to avoid"
    )


class TroubleshootingTip(BaseModel):
    """A troubleshooting tip for common issues.

    Provides guidance for problems users commonly encounter
    during cabinet assembly.

    Attributes:
        issue: The problem encountered
        cause: Likely cause of the issue
        solution: How to fix or work around the issue
        prevention: How to prevent this issue in the future
    """

    issue: str = Field(description="The problem encountered")
    cause: str = Field(description="Likely cause of the issue")
    solution: str = Field(description="How to fix or work around the issue")
    prevention: str | None = Field(
        default=None, description="How to prevent this issue"
    )


class AssemblyInstructions(BaseModel):
    """Complete assembly instructions output from LLM.

    This is the main structured output schema that the LLM
    generates. It contains all sections of the assembly guide.

    Attributes:
        title: Document title
        skill_level: Target skill level for these instructions
        cabinet_summary: Brief description of the cabinet being built
        estimated_time: Total estimated assembly time
        safety_warnings: Safety warnings for this project
        tools_needed: Tools required for assembly
        materials_checklist: Materials to verify before starting
        steps: Step-by-step assembly instructions
        troubleshooting: Troubleshooting tips for common issues
        finishing_notes: Notes for finishing and final assembly
        generated_by: Indicates how instructions were generated
    """

    title: str = Field(description="Document title")
    skill_level: Literal["beginner", "intermediate", "expert"] = Field(
        description="Target skill level"
    )
    cabinet_summary: str = Field(
        description="Brief description of the cabinet being built"
    )
    estimated_time: str = Field(description="Total estimated assembly time")
    safety_warnings: list[SafetyWarning] = Field(
        description="Safety warnings for this project"
    )
    tools_needed: list[ToolRecommendation] = Field(
        description="Tools required for assembly"
    )
    materials_checklist: list[str] = Field(
        description="Materials to verify before starting"
    )
    steps: list[AssemblyStep] = Field(description="Step-by-step assembly instructions")
    troubleshooting: list[TroubleshootingTip] = Field(
        default_factory=list, description="Troubleshooting tips for common issues"
    )
    finishing_notes: str = Field(description="Notes for finishing and final assembly")
    generated_by: Literal["llm", "template"] = Field(
        default="llm", description="Indicates how instructions were generated"
    )


class AssemblyDeps(BaseModel):
    """Dependencies injected into the assembly agent.

    Contains all the context data needed by the LLM to generate
    appropriate assembly instructions for a specific cabinet.

    Note: Uses arbitrary_types_allowed for domain objects that
    are not JSON-serializable by default.

    Attributes:
        cabinet: The cabinet entity being assembled
        cut_list: List of cut pieces for the cabinet
        joinery: List of joinery connections
        skill_level: Target skill level for instructions
        material_type: Primary material type
        has_doors: Whether cabinet has doors
        has_drawers: Whether cabinet has drawers
        has_decorative_elements: Whether cabinet has decorative elements
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    cabinet: Cabinet
    cut_list: list[CutPiece]
    joinery: list[Any]  # list[ConnectionJoinery] - using Any to avoid circular import
    skill_level: Literal["beginner", "intermediate", "expert"]
    material_type: MaterialType
    has_doors: bool = False
    has_drawers: bool = False
    has_decorative_elements: bool = False
