"""Unit tests for SafetyReportFormatter."""

from __future__ import annotations


from cabinets.domain.services.safety import (
    ADA_DISCLAIMER,
    MATERIAL_DISCLAIMER,
    SAFETY_GENERAL_DISCLAIMER,
    AccessibilityReport,
    SafetyAssessment,
    SafetyCheckResult,
    SafetyLabel,
    WeightCapacityEstimate,
)
from cabinets.domain.value_objects import (
    ADAStandard,
    SafetyCategory,
    SafetyCheckStatus,
)
from cabinets.infrastructure.formatters import SafetyReportFormatter


class TestSafetyReportFormatterBasic:
    """Test basic SafetyReportFormatter functionality."""

    def test_format_minimal_assessment(self) -> None:
        """Test formatting a minimal assessment with no checks."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "# Safety Assessment Report" in report
        assert "## Summary" in report
        assert "## Disclaimers" in report

    def test_format_generates_valid_markdown(self) -> None:
        """Test that formatter generates valid markdown structure."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="Test passed",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        # Check markdown structure
        assert report.startswith("# Safety Assessment Report")
        assert "Generated by Cabinet Layout Generator" in report


class TestSafetyReportFormatterSummary:
    """Test summary section formatting."""

    def test_format_summary_passed(self) -> None:
        """Test summary shows PASSED status."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="All good",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "**PASSED** - All safety checks passed" in report
        assert "Errors: 0" in report
        assert "Warnings: 0" in report

    def test_format_summary_passed_with_warnings(self) -> None:
        """Test summary shows PASSED with WARNINGS status."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.MATERIAL,
                    status=SafetyCheckStatus.WARNING,
                    message="Material warning",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "**PASSED with WARNINGS** - Review recommended" in report
        assert "Errors: 0" in report
        assert "Warnings: 1" in report

    def test_format_summary_failed(self) -> None:
        """Test summary shows FAILED status."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.ERROR,
                    message="Clearance violation",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "**FAILED** - Safety issues require attention" in report
        assert "Errors: 1" in report

    def test_format_summary_anti_tip_required(self) -> None:
        """Test summary shows anti-tip requirement."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=True,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "**Anti-tip restraint is required for this cabinet.**" in report


class TestSafetyReportFormatterWeightCapacity:
    """Test weight capacity section formatting."""

    def test_format_weight_capacity_table(self) -> None:
        """Test weight capacity table formatting."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[
                WeightCapacityEstimate(
                    panel_id="section_0_shelf_0",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=22.5,
                ),
                WeightCapacityEstimate(
                    panel_id="section_0_shelf_1",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=22.5,
                ),
            ],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Weight Capacity" in report
        assert "| Shelf | Capacity | Material | Span | Safety Factor |" in report
        assert "section_0_shelf_0" in report
        assert "45 lbs" in report
        assert "plywood" in report
        assert '22.5"' in report
        assert "4:1" in report

    def test_format_structural_analysis(self) -> None:
        """Test structural analysis results in weight capacity section."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="weight_capacity_shelf_0",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="shelf_0: 45 lbs capacity (meets KCMA standard)",
                    standard_reference="ANSI/KCMA A161.1",
                )
            ],
            weight_capacities=[
                WeightCapacityEstimate(
                    panel_id="shelf_0",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=36.0,
                ),
            ],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "### Structural Analysis" in report
        assert "[PASS]" in report
        assert "meets KCMA standard" in report
        assert "ANSI/KCMA A161.1" in report


class TestSafetyReportFormatterStability:
    """Test stability section formatting."""

    def test_format_stability_section(self) -> None:
        """Test stability section with anti-tip warning."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="anti_tip_requirement",
                    category=SafetyCategory.STABILITY,
                    status=SafetyCheckStatus.WARNING,
                    message='Anti-tip restraint required: Cabinet height 60.0" exceeds 27" threshold',
                    remediation="Install anti-tip strap or bracket to secure cabinet to wall.",
                    standard_reference="ASTM F2057-23 (guidance)",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=True,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Stability" in report
        assert "[WARN]" in report
        assert "Anti-tip restraint required" in report
        assert "*Suggestion:" in report
        assert "ASTM F2057-23" in report
        assert "### Anti-Tip Hardware Required" in report
        assert "must be anchored to the wall" in report


class TestSafetyReportFormatterAccessibility:
    """Test accessibility section formatting."""

    def test_format_accessibility_compliant(self) -> None:
        """Test accessibility section for compliant cabinet."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=AccessibilityReport(
                total_storage_volume=10000.0,
                accessible_storage_volume=6500.0,
                accessible_percentage=65.0,
                is_compliant=True,
                non_compliant_areas=(),
                reach_violations=(),
                hardware_notes=(
                    "ADA: Select hardware operable without tight grasping, pinching, or wrist twisting",
                    "Recommended: Lever-style handles, D-pulls, or loop handles",
                ),
                standard=ADAStandard.ADA_2010,
            ),
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Accessibility (ADA)" in report
        assert "Status: **COMPLIANT**" in report
        assert "Accessible Storage: 65.0%" in report
        assert "Required Minimum: 50%" in report
        assert "ADA_2010" in report
        assert "### Hardware Recommendations" in report
        assert "Lever-style handles" in report

    def test_format_accessibility_non_compliant(self) -> None:
        """Test accessibility section for non-compliant cabinet."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=AccessibilityReport(
                total_storage_volume=10000.0,
                accessible_storage_volume=3500.0,
                accessible_percentage=35.0,
                is_compliant=False,
                non_compliant_areas=('Section 0, Shelf 2: height 52.0" from floor',),
                reach_violations=(
                    'Section 0, Shelf 2: Shelf at 52.0" exceeds 48" unobstructed reach maximum',
                ),
                hardware_notes=(),
                standard=ADAStandard.ADA_2010,
            ),
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "Status: **NON-COMPLIANT**" in report
        assert "Accessible Storage: 35.0%" in report
        assert "### Reach Range Violations" in report
        assert 'exceeds 48" unobstructed reach maximum' in report
        assert "### Non-Compliant Areas" in report


class TestSafetyReportFormatterClearances:
    """Test clearances section formatting."""

    def test_format_clearances_pass(self) -> None:
        """Test clearances section with passing checks."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="clearance_summary",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.PASS,
                    message="All clearance requirements met",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Building Code Clearances" in report
        assert "[PASS]" in report
        assert "All clearance requirements met" in report

    def test_format_clearances_error(self) -> None:
        """Test clearances section with error."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="electrical_panel_clearance",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.ERROR,
                    message="Building Code Violation: Cabinet encroaches on electrical panel clearance zone",
                    remediation='Maintain minimum 30" clear width and 36" clear depth in front of electrical panel per NEC Article 110.26',
                    standard_reference="NEC Article 110.26",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Building Code Clearances" in report
        assert "[FAIL]" in report
        assert "Building Code Violation" in report
        assert "*Suggestion:" in report
        assert "NEC Article 110.26" in report


class TestSafetyReportFormatterMaterialSafety:
    """Test material safety section formatting."""

    def test_format_material_safety_warning(self) -> None:
        """Test material safety section with warning."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="material_certification",
                    category=SafetyCategory.MATERIAL,
                    status=SafetyCheckStatus.WARNING,
                    message="Material certification not specified",
                    remediation="Verify CARB Phase 2 compliance for US sales.",
                    standard_reference="CARB ATCM 93120 / EPA TSCA Title VI",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Material Safety" in report
        assert "[WARN]" in report
        assert "Material certification not specified" in report
        assert "CARB Phase 2" in report
        assert "CARB ATCM 93120" in report


class TestSafetyReportFormatterSeismic:
    """Test seismic section formatting."""

    def test_format_seismic_section(self) -> None:
        """Test seismic section with hardware requirements."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="seismic_zone",
                    category=SafetyCategory.SEISMIC,
                    status=SafetyCheckStatus.WARNING,
                    message="Seismic Zone D: Enhanced anchoring required",
                    remediation="Use seismic-rated anchoring hardware.",
                    standard_reference="CBC Section 1617A / IBC Seismic",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[
                "Seismic-rated wall anchor (qty: per mounting point)",
                'Steel angle bracket with 1/4" lag screws (qty: 2 per cabinet)',
            ],
        )

        report = formatter.format(assessment)

        assert "## Seismic Requirements" in report
        assert "[WARN]" in report
        assert "Seismic Zone D" in report
        assert "### Required Hardware" in report
        assert "Seismic-rated wall anchor" in report
        assert "Steel angle bracket" in report


class TestSafetyReportFormatterChildSafety:
    """Test child safety section formatting."""

    def test_format_child_safety_section(self) -> None:
        """Test child safety section with recommendations."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="child_safety_tip_over",
                    category=SafetyCategory.CHILD_SAFETY,
                    status=SafetyCheckStatus.WARNING,
                    message="CHILD SAFETY: Furniture tip-over is a leading cause of injury to children.",
                    remediation="Install anti-tip restraint before use. Do not allow children to climb on furniture.",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=True,
            seismic_hardware=[],
            child_safety_notes=[
                "Use soft-close hinges to prevent finger injuries",
                "Install child safety locks on lower cabinets",
            ],
        )

        report = formatter.format(assessment)

        assert "## Child Safety" in report
        assert "[WARN]" in report
        assert "tip-over" in report
        assert "### Recommendations" in report
        assert "soft-close hinges" in report
        assert "child safety locks" in report


class TestSafetyReportFormatterSafetyLabels:
    """Test safety labels section formatting."""

    def test_format_safety_labels_section(self) -> None:
        """Test safety labels section."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[
                SafetyLabel(
                    label_type="weight_capacity",
                    title="MAXIMUM LOAD",
                    body_text="Do not exceed 45 lbs per shelf.",
                    warning_icon=True,
                    dimensions=(4.0, 2.0),
                ),
                SafetyLabel(
                    label_type="anti_tip",
                    title="WARNING: TIP-OVER HAZARD",
                    body_text="To reduce the risk of tip-over, this furniture must be anchored to the wall.",
                    warning_icon=True,
                    dimensions=(4.0, 3.0),
                ),
            ],
            anti_tip_required=True,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Safety Labels" in report
        assert "### MAXIMUM LOAD" in report
        assert "Type: weight_capacity" in report
        assert '4.0" x 2.0"' in report
        assert "Includes warning icon" in report
        assert "### WARNING: TIP-OVER HAZARD" in report


class TestSafetyReportFormatterDisclaimers:
    """Test disclaimers section formatting."""

    def test_format_disclaimers_always_present(self) -> None:
        """Test that disclaimers are always present in report."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Disclaimers" in report
        assert "**General:**" in report
        assert "advisory only" in report.lower()
        assert "**Accessibility:**" in report
        assert "**Materials:**" in report

    def test_format_disclaimers_content(self) -> None:
        """Test disclaimer content matches constants."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert SAFETY_GENERAL_DISCLAIMER in report
        assert ADA_DISCLAIMER in report
        assert MATERIAL_DISCLAIMER in report


class TestSafetyReportFormatterStatusIcons:
    """Test status icon formatting."""

    def test_pass_icon(self) -> None:
        """Test PASS status shows correct icon."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="Test passed",
                )
            ],
            weight_capacities=[
                WeightCapacityEstimate(
                    panel_id="shelf_0",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=36.0,
                ),
            ],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "[PASS]" in report

    def test_warning_icon(self) -> None:
        """Test WARNING status shows correct icon."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.STABILITY,
                    status=SafetyCheckStatus.WARNING,
                    message="Test warning",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "[WARN]" in report

    def test_error_icon(self) -> None:
        """Test ERROR status shows correct icon."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.ERROR,
                    message="Test error",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "[FAIL]" in report

    def test_not_applicable_icon(self) -> None:
        """Test NOT_APPLICABLE status shows correct icon."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="test",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.NOT_APPLICABLE,
                    message="Test N/A",
                )
            ],
            weight_capacities=[],
            accessibility_report=None,
            safety_labels=[],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "[N/A]" in report


class TestSafetyReportFormatterFullReport:
    """Test full report with all sections."""

    def test_format_full_assessment(self) -> None:
        """Test formatting a full assessment with all categories."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="weight_capacity_shelf_0",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="shelf_0: 45 lbs capacity (meets KCMA standard)",
                    standard_reference="ANSI/KCMA A161.1",
                ),
                SafetyCheckResult(
                    check_id="anti_tip_requirement",
                    category=SafetyCategory.STABILITY,
                    status=SafetyCheckStatus.WARNING,
                    message='Anti-tip restraint required: Cabinet height 60.0" exceeds 27" threshold',
                    remediation="Install anti-tip strap or bracket to secure cabinet to wall.",
                    standard_reference="ASTM F2057-23 (guidance)",
                ),
                SafetyCheckResult(
                    check_id="clearance_summary",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.PASS,
                    message="All clearance requirements met",
                ),
                SafetyCheckResult(
                    check_id="material_certification",
                    category=SafetyCategory.MATERIAL,
                    status=SafetyCheckStatus.WARNING,
                    message="Material certification not specified",
                    remediation="Verify CARB Phase 2 compliance for US sales.",
                    standard_reference="CARB ATCM 93120 / EPA TSCA Title VI",
                ),
            ],
            weight_capacities=[
                WeightCapacityEstimate(
                    panel_id="section_0_shelf_0",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=22.5,
                ),
            ],
            accessibility_report=AccessibilityReport(
                total_storage_volume=10000.0,
                accessible_storage_volume=6500.0,
                accessible_percentage=65.0,
                is_compliant=True,
                non_compliant_areas=(),
                reach_violations=(),
                hardware_notes=(
                    "ADA: Select hardware operable without tight grasping",
                ),
                standard=ADAStandard.ADA_2010,
            ),
            safety_labels=[],
            anti_tip_required=True,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        # Verify all sections present
        assert "# Safety Assessment Report" in report
        assert "## Summary" in report
        assert "## Weight Capacity" in report
        assert "## Stability" in report
        assert "## Accessibility (ADA)" in report
        assert "## Building Code Clearances" in report
        assert "## Material Safety" in report
        assert "## Disclaimers" in report

        # Verify summary counts
        assert "Errors: 0" in report
        assert "Warnings: 2" in report
        assert "**PASSED with WARNINGS**" in report

    def test_format_all_sections_included(self) -> None:
        """Test that all applicable sections are included."""
        formatter = SafetyReportFormatter()
        assessment = SafetyAssessment(
            check_results=[
                SafetyCheckResult(
                    check_id="structural",
                    category=SafetyCategory.STRUCTURAL,
                    status=SafetyCheckStatus.PASS,
                    message="Structural OK",
                ),
                SafetyCheckResult(
                    check_id="stability",
                    category=SafetyCategory.STABILITY,
                    status=SafetyCheckStatus.PASS,
                    message="Stability OK",
                ),
                SafetyCheckResult(
                    check_id="clearance",
                    category=SafetyCategory.CLEARANCE,
                    status=SafetyCheckStatus.PASS,
                    message="Clearance OK",
                ),
                SafetyCheckResult(
                    check_id="material",
                    category=SafetyCategory.MATERIAL,
                    status=SafetyCheckStatus.PASS,
                    message="Material OK",
                ),
                SafetyCheckResult(
                    check_id="seismic",
                    category=SafetyCategory.SEISMIC,
                    status=SafetyCheckStatus.PASS,
                    message="Seismic OK",
                ),
                SafetyCheckResult(
                    check_id="child",
                    category=SafetyCategory.CHILD_SAFETY,
                    status=SafetyCheckStatus.PASS,
                    message="Child safety OK",
                ),
            ],
            weight_capacities=[
                WeightCapacityEstimate(
                    panel_id="shelf",
                    safe_load_lbs=45.0,
                    max_deflection_inches=0.18,
                    deflection_at_rated_load=0.045,
                    safety_factor=4.0,
                    material="plywood",
                    span_inches=36.0,
                ),
            ],
            accessibility_report=AccessibilityReport(
                total_storage_volume=1000.0,
                accessible_storage_volume=600.0,
                accessible_percentage=60.0,
                is_compliant=True,
                non_compliant_areas=(),
                reach_violations=(),
                hardware_notes=(),
                standard=ADAStandard.ADA_2010,
            ),
            safety_labels=[
                SafetyLabel(
                    label_type="weight_capacity",
                    title="MAXIMUM LOAD",
                    body_text="Test",
                    warning_icon=False,
                ),
            ],
            anti_tip_required=False,
            seismic_hardware=[],
        )

        report = formatter.format(assessment)

        assert "## Weight Capacity" in report
        assert "## Stability" in report
        assert "## Accessibility (ADA)" in report
        assert "## Building Code Clearances" in report
        assert "## Material Safety" in report
        assert "## Seismic Requirements" in report
        assert "## Child Safety" in report
        assert "## Safety Labels" in report
        assert "## Disclaimers" in report
